test: add CI tweak

diff --git a/.github/workflows/build:test.yml b/.github/workflows/build:test.yml
--- a/.github/workflows/build:test.yml
+++ b/.github/workflows/build:test.yml
@@ -19,13 +19,33 @@ jobs:
           node-version: latest
           registry-url: 'https://registry.npmjs.org'
       - run: |
-          JSONHasValidKey() {
+          validate() {
+            $1 $2 $3
+            
+            keys=$(jq -n "$1" )
+            required=$2
+            name=$3
 
+            for i in "${required[@]}"
+              do
+              exists=$(jq 'has('\"$i\"')' <<< $keys)
+              value=$(jq  ".$i" <<< $keys)
+
+              if [ $exists == true ]; then
+                if [ -z "${value}" ]; then
+                  echo "::error title=param. empty::$i exists but is empty"
+                  exit 1
+                fi
+              else
+                echo "::error title=param. missing::$i missing from $name"
+                exit 1
+              fi
+            done
           }
           
           required=("NPM_TOKEN" "github_token" "mouse")
 
-          JSONHasValidKey $secrets $required "secrets"
+          validate $secrets $required "secrets"
         name: Verify required parameters
         env:
           secrets: ${{ toJSON(secrets) }}
