test: CI tweaks

diff --git a/.github/workflows/test:size.yml b/.github/workflows/test:size.yml
--- a/.github/workflows/test:size.yml
+++ b/.github/workflows/test:size.yml
@@ -38,9 +38,11 @@ jobs:
     #   - if yes, print err message and exit 1
     - run: |
         size=$(wc -c < dist/main.mjs.gz | tr -d '[:space:]');
+        echo "::notice title=size:: file size is: ${size} bytes";
         test "$size" -lt "$BYTE_LIMIT" &&
-        echo "::notice title=size ok::${size} within ${BYTE_LIMIT} bytes limit" ||
-        (echo "::error title=too big::${size} bytes > ${BYTE_LIMIT} bytes" >&2 && exit 1);
+        echo "::notice title=size ok::size within ${BYTE_LIMIT} bytes limit" ||
+        (echo "::error title=too big::size exceeds ${BYTE_LIMIT} bytes limit" 
+        >&2 && exit 1);
       env:
         BYTE_LIMIT: 500
     # cleanup
