test: CI tweaks

diff --git a/.github/workflows/test:size.yml b/.github/workflows/test:size.yml
--- a/.github/workflows/test:size.yml
+++ b/.github/workflows/test:size.yml
@@ -39,11 +39,8 @@ jobs:
     - run: |
         size=$(wc -c < dist/main.mjs.gz | tr -d '[:space:]');
         test "$size" -lt "$BYTE_LIMIT" &&
-        echo "::notice title=size ok::${size} within ${BYTE_LIMIT} bytes limit" 
-        || (
-          echo "::error title=size too big::${size} bytes > ${BYTE_LIMIT} bytes" 
-          >&2 && exit 1
-        );
+        echo "::notice title=size ok::${size} within ${BYTE_LIMIT} bytes limit" ||
+        (echo "::error title=too big::${size} bytes > ${BYTE_LIMIT} bytes" >&2 && exit 1);
       env:
         BYTE_LIMIT: 500
     # cleanup
