test: test

diff --git a/.github/workflows/test:deps.yml b/.github/workflows/test:deps.yml
--- a/.github/workflows/test:deps.yml
+++ b/.github/workflows/test:deps.yml
@@ -43,24 +43,26 @@ jobs:
     - run: | 
         deps=$(npm pkg get dependencies);
         depsCount=$(echo "$deps" | tr -cd ':' | wc -c);
+        echo "deps=$deps" >> "$GITHUB_OUTPUT";
         echo "depsCount=$depsCount" >> "$GITHUB_OUTPUT";
         echo "depsCount=$depsCount" >> "$GITHUB_ENV";
-        echo "deps=$deps" >> "$GITHUB_ENV";
         
         ddeps=$(npm pkg get devDependencies);
         ddepsCount=$(echo "$ddeps" | tr -cd ':' | wc -c);
+        echo "ddeps=$ddeps" >> "$GITHUB_OUTPUT";
         echo "ddepsCount=$ddepsCount" >> "$GITHUB_OUTPUT";
         echo "ddepsCount=$ddepsCount" >> "$GITHUB_ENV";
-        echo "ddeps=$ddeps" >> "$GITHUB_ENV";
       name: get dependencies and devDependencies count
       id: package
 
     # check runtime dependencies
     - run: |
-        t="too many dependencies" && \
+        ta="too many dependencies" && \
+        tb="dependencies" && \
         e="Lists ${depsCount} dependencies. Max limit: ${MAX_DEPS}." && \
-        echo "::error title=${t}::${e}." && 
-        echo "::error title=dependencies::${deps}." && exit 1
+        echo "::error title=${ta}::${e}." && \
+        echo "::error title=${tb}::${{ steps.package.outputs.deps }}" && \
+        exit 1
 
       if: fromJSON(steps.package.outputs.depsCount) > fromJSON(env.MAX_DEPS)
       name: Too Many Dependencies Error
