test: CI tweaks

diff --git a/.github/workflows/test:size.yml b/.github/workflows/test:size.yml
--- a/.github/workflows/test:size.yml
+++ b/.github/workflows/test:size.yml
@@ -55,6 +55,14 @@ jobs:
       name: Get compressed size, in bytes
       id: getsize
 
+    # if size = 0, err message & exit 1
+    - run: |
+        t="bundle is empty" && \
+        echo "::error title=${t}::size: ${size} B = 0 B. Bundle is empty."; \
+        exit 1
+      if: fromJSON(steps.getsize.outputs.size) = 0
+      name: if size = 0, Bundle Empty Error
+
     # if size > limit, err message & exit 1
     - run: |
         t="bundle size limit exceeded" && \
@@ -63,7 +71,7 @@ jobs:
       if: fromJSON(steps.getsize.outputs.size) > fromJSON(env.LIMIT_BYTES)
       name: if size > limit, Size Exceeded Error
 
-    # else if size <= limit, sucess message & exit
+    # else if size <= limit, sucess message & exit 0
     - run: |
         t="size limit OK" && \
         echo "::notice title=${t}::size: ${size} B <= limit: ${LIMIT_BYTES} B"
