test: CI tweaks

diff --git a/.github/workflows/test:size.yml b/.github/workflows/test:size.yml
--- a/.github/workflows/test:size.yml
+++ b/.github/workflows/test:size.yml
@@ -22,17 +22,17 @@ jobs:
         cache: 'npm'
     - run: npm ci
     - run: npm i -D webpack-cli
-    # Bundle & minify src/index.js 
+    # bundle/minify src/index.js 
     - run: npx webpack --mode production --output-library-type module --experiments-output-module
-    # compress it
+    # gzip it
     - run: gzip dist/main.mjs
-    # Get gzip size, compare > BYTE_LIMIT, print message, exit 1 if yes
+    # get gzip size, compare > BYTE_LIMIT, print message, exit 1 if yes
     - run: >
-        size=$(wc -c < dist/main.mjs.gz | tr -d '[:space:]');\ 
-          test "$size" -lt "$BYTE_LIMIT" &&\
-          echo "size ${size} bytes within ${BYTE_LIMIT} bytes limit" ||\ 
-          (echo "size ${size} bytes > ${BYTE_LIMIT} bytes limit" >&2 && exit 1);  
+          size=$(wc -c < dist/main.mjs.gz | tr -d '[:space:]');\ 
+            test "$size" -lt "$BYTE_LIMIT" &&\
+            echo "size ${size} bytes within ${BYTE_LIMIT} bytes limit" ||\ 
+            (echo "size ${size} bytes > ${BYTE_LIMIT} bytes limit" >&2 && exit 1);  
       env:
         BYTE_LIMIT: 999
-    # Cleanup
+    # cleanup
     - run: npm r -D webpack-cli; rm -rf dist/
